### ISSUE TITLE
Prefer Immutable Java Records over Lombok powered DTOs

### ISSUE THREAD

**Issue by eharrow** [surrealdb/surrealdb.java#21]
Hi

Great work.

Java records are the way to go IMHO for DTOs so with this in mind can we make this simple change while the codebase is very small?

I have created the following PR https://github.com/surrealdb/surrealdb.java/pull/20

**Comment by eharrow** [comment]
> Hey @eharrow, thanks for opening the change. I am not very familiar with records, but I understand that they are read-only structs. I remember trying to use them and I had issues that seemed unnecessary. Having a quick read online - my challenge may have been being unable to extend records. This means that we would be sacrificing malleability for no foreseeable benefits. You can still have immutability in regular POJOs.
> 
> Therefore given that records offer little benefit beyond pojos+lombok, I would rather stick with pojos and lombok.

I understand your choice and in the java world as we further embrace functional programming immutability is a requirement and records enforce this and communicate it to api consumers.

**Comment by phughk** [comment]
I love functional programming, but not everything should be expressed functionally because we can. The GC overhead is non-negligible, and imperative procedural programming can be clearer and more performant (while still being safe). Like every decision, things must be contextual.

That said, I can't deny there will be a trend from users and from dependencies to prefer records, so I agree that we can make records the default and DTOs the exception. One concern I have is how we will find out the pain points of such decisions, as users seldom jump onto GitHub to provide examples of how the API is bad because they can't extend or use it the way they want.

Closing as I agree with the decision.
